"""State owned by visualization creation and settings panels."""


STANDARD_PLOT_COLORS = [
    "#c00000",
    "#ff0000",
    "#ffc000",
    "#ffff00",
    "#92d050",
    "#00b050",
    "#00b0f0",
    "#0070c0",
    "#002060",
    "#7030a0",
    "#000000",
]


def defaults():
    return {
        "scalarPlotPolicy": "always",
        "scalarPlotAlwaysForSession": False,
        "showScalarPlotDialog": False,
        "pendingScalarPlotVariableId": "",
        "pendingScalarPlotCellIndex": -1,
        "pendingScalarPlotSourceFields": {},
        "pendingScalarPlotSyncSelection": True,
        "scalarPlotDialogMessage": "",
        "scalarPlotStatus": "",
        "showPlotSettingsModal": False,
        "plotSettingsCellIndex": -1,
        "plotSettingsTitle": "",
        "plotSettingsStatus": "",
        "plotSettingsCanPluginOptions": False,
        "plotSettingsXAuto": True,
        "plotSettingsXMin": "",
        "plotSettingsXMax": "",
        "plotSettingsXScale": "linear",
        "plotSettingsYAuto": True,
        "plotSettingsYMin": "",
        "plotSettingsYMax": "",
        "plotSettingsYScale": "linear",
        "plotSettingsLineWidth": 2.5,
        "plotSettingsShowGrid": True,
        "plotSettingsShowCursor": True,
        "plotSettingsBackgroundColor": "#ffffff",
        "plotSettingsGridColor": "#e8e8e8",
        "plotSettingsCursorColor": "#111111",
        "plotSettingsSeriesRows": [],
        "plotSettingsStandardColors": list(STANDARD_PLOT_COLORS),
        "showPluginOptionsModal": False,
        "pluginOptionsCellIndex": -1,
        "pluginOptionsTitle": "",
        "pluginOptionsStatus": "",
        "pluginOptionsRows": [],
        "showScalarFieldSettingsModal": False,
        "scalarFieldSettingsCellIndex": -1,
        "scalarFieldSettingsTitle": "",
        "scalarFieldSettingsStatus": "",
        "scalarFieldSettingsStatusIsError": False,
        "scalarFieldSettingsColormap": "viridis",
        "scalarFieldSettingsRangeAuto": True,
        "scalarFieldSettingsMin": "",
        "scalarFieldSettingsMax": "",
        "scalarFieldSettingsShowColorbar": False,
        "scalarFieldSettingsShowAxes": False,
    }


def right_pane_reset_defaults():
    return {
        "showScalarPlotDialog": False,
        "pendingScalarPlotVariableId": "",
        "pendingScalarPlotCellIndex": -1,
        "pendingScalarPlotSourceFields": {},
        "scalarPlotDialogMessage": "",
        "showPlotSettingsModal": False,
        "plotSettingsCellIndex": -1,
        "plotSettingsTitle": "",
        "plotSettingsStatus": "",
        "plotSettingsCanPluginOptions": False,
        "plotSettingsBackgroundColor": "#ffffff",
        "plotSettingsGridColor": "#e8e8e8",
        "plotSettingsCursorColor": "#111111",
        "plotSettingsSeriesRows": [],
        "showPluginOptionsModal": False,
        "pluginOptionsCellIndex": -1,
        "pluginOptionsTitle": "",
        "pluginOptionsStatus": "",
        "pluginOptionsRows": [],
        "showScalarFieldSettingsModal": False,
        "scalarFieldSettingsCellIndex": -1,
        "scalarFieldSettingsTitle": "",
        "scalarFieldSettingsStatus": "",
        "scalarFieldSettingsStatusIsError": False,
        "scalarFieldSettingsColormap": "viridis",
        "scalarFieldSettingsRangeAuto": True,
        "scalarFieldSettingsMin": "",
        "scalarFieldSettingsMax": "",
        "scalarFieldSettingsShowColorbar": False,
        "scalarFieldSettingsShowAxes": False,
    }
